version: '3.8'

services:
  api-clinica:
    container_name: api-clinica
    build:
      context: ./
    restart: always
    ports:
      - 3001:3000
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # - DATABASE_HOST=127.0.0.1
      # - POSTGRES_USER=root
      # - POSTGRES_PASSWORD=root
      # - POSTGRES_DB=DB_Clinica
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
